version: '3.9'

services:
  postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_api
    ports:
      - 5432:5432
    volumes:
      - ./.artifacts/:/var/lib/postgresql/data
    networks:
      - web

  app:
    build:
      context: .
      dockerfile: cmd/Dockerfile
    ports:
      - 8000:8000
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - web

networks:
  web:
    name: web