version: '3.9'

services:
  postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_api
    ports:
      - 5432:5432
    volumes:
      - ./.artifacts/:/var/lib/postgresql/data

